### ISSUE TITLE
How to  get Oxford RobotCar with one image sampled every 5 meters ?

### ISSUE THREAD

**Issue by wpumain** [valeriopaolicelli/SegVPR#4]
Think you  for your excellent work！
I know I can download data from this website 【https://robotcar-dataset.robots.ox.ac.uk/datasets】，but how to  get Oxford RobotCar with one image sampled every 5 meters ?
May you help me ?

**Comment by valeriopaolicelli** [comment]
Hello @wpumain, thanks for your question. 
Sorry for the late response but I’m no more supporting and monitoring this project. Hope you have solved this issue.
Anyway, I remember that the Oxford Robocar dataset comes with lot of metadata for each frame. You can easily sample your subset by using the GPS coordinates. 
If you have downloaded the dataset, you can try following this procedure:
- group the images by weather conditions
- sort each group by timestamp 
- for each image, compute the distance between its coordinates and those of the previous sampled frame
- keep the image if the distance is at least 5, discard it otherwise

**Comment by wpumain** [comment]
Can you share the dataset that you used to train this model?Think you。

**Comment by valeriopaolicelli** [comment]
Hello, unfortunately I cannot share it. It is provided by the original authors on a dedicated website. Moreover, since I'm no longer working on this project, I don't have access to its resources. I strongly recommend that you download the Oxford RobotCar dataset from the original website and follow the above procedure (or something similar) to sample a subset for each weather condition.

**Comment by wpumain** [comment]
Think you for your reply
